### ISSUE TITLE
Добавить настройки codeStyle для проекта

### ISSUE THREAD

**Issue by Avenlisp** [VDraks/School-Desk#15]

**Comment by flipp5b** [comment]
Добавил настройки code style для IntellijIDEA в папку ide-settings в корне проекта.

Еще давно уже есть страничка в вики: https://github.com/VDraks/School-Desk/wiki/Code-Style. Так что предлагаю излагать туда свои мысли по стилю кода.

UPD: там сейчас выставлена ширина таба -- 2 символа, можно ставить 4 (или кому как удобно); единственное, чтобы соблюдались правила:
- ширина таба = ширина отступа (т. е., например, 4 и 4 или 2 и 2);
- размер continuation indent (не знаю, как правильно по-русски) = 2x ширины таба
