### ISSUE TITLE
Добавить интерфейсы DAO для новых сущностей + пересмотреть сущности

### ISSUE THREAD

**Issue by Avenlisp** [VDraks/School-Desk#16]
Насчет пересмотра сущностей: я думаю, что DTO может содержать коллекцию из сущностей, если эти сущности легковесны или же не планируется добавлять DAO для их подгрузки.
Так, например, вопрос теста не имеет особого смысла, как отдельная сущность и, по-хорошему, должен возвращаться вместе с тестом.
Т.е. я предлагаю пересмотреть существующие DTO и заменить коллекции айдишников на коллекции DTO и т.п. там, где они особо не нужны.

**Comment by flipp5b** [comment]
Похоже, что интерфейсы DAO более или меннее стабилизировались.

**Comment by Avenlisp** [comment]
Хорошо
